.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "HEIFIZE" "1" "March 2023" "" "Jessica Stokes' Dotfiles"
.
.SH "NAME"
\fBheifize\fR \- creates HEIF copies of images
.
.SH "SYNOPSIS"
\fBheifize\fR [\fIimage\fR\.\.\.] \fIimage\fR
.
.SH "DESCRIPTION"
The heifize(1) command creates HEIF copies of image file arguments, while preserving metadata
.
.P
The output filename is the original filename with a "heif" extension
.
.P
If parallel(1) is available, the operations will be parallelised to run on all CPU cores
.
.SH "OPTIONS"
.
.TP
\fIimage\fR
any image file sips supports\.
.
.SH "SEE ALSO"
sips(1), parallel(1)
