.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "JXLIFY" "1" "April 2025" "" "Jessica Stokes' Dotfiles"
.
.SH "NAME"
\fBjxlify\fR \- creates HEIF copies of images
.
.SH "SYNOPSIS"
\fBjxlify\fR [\fIimage\fR\.\.\.] \fIimage\fR
.
.SH "DESCRIPTION"
The jxlify(1) command creates JPEG\-XL copies of image file arguments, while preserving metadata
.
.P
The output filename is the original filename with a "jxl" extension
.
.SH "OPTIONS"
.
.TP
\fIimage\fR
any image file cjxl supports\.
.
.SH "SEE ALSO"
heifize(1), cjxl(1), xargs(1)
