.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "NP" "1" "March 2015" "" "Jessica Stokes' Dotfiles"
.
.SH "NAME"
\fBnp\fR \- current iTunes playback information
.
.SH "SYNOPSIS"
\fBnp\fR
.
.SH "DESCRIPTION"
The np(1) command displays the details of the current playing track in iTunes\.
.
.SH "SEE ALSO"
nps(1)
