.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "PBCOPYFILE" "1" "January 2016" "" "Jessica Stokes' Dotfiles"
.
.SH "NAME"
\fBpbcopyfile\fR \- copy a file to the pasteboard
.
.SH "SYNOPSIS"
\fBpbcopyfile\fR \fIfile\fR
.
.SH "DESCRIPTION"
The pbcopyfile(1) command copies the specified file to the pasteboard (the Clipboard)\.
.
.P
Copied from this StackOverflow answer: http://apple\.stackexchange\.com/a/15542
.
.SH "SEE ALSO"
pbcopy(1), pbpaste(1)
