.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "TWEETBOT\-THUMBNAILS\-ON" "1" "March 2015" "" "Jessica Stokes' Dotfiles"
.
.SH "NAME"
\fBtweetbot\-thumbnails\-on\fR \- turn thumbnails on in Tweetbot
.
.SH "SYNOPSIS"
\fBtweetbot\-thumbnails\-on\fR
.
.SH "DESCRIPTION"
The tweetbot\-thumbnails\-on(1) command turns thumbnails on in Tweetbot, and restarts the app if it\'s running\.
.
.SH "SEE ALSO"
textual\-thumbnails\-off(1) textual\-thumbnails\-on(1) tweetbot\-thumbnails\-off(1)
