.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "28POINT8" "1" "September 2014" "" "Geoff Stokes' Dotfiles"
.
.SH "NAME"
\fB28point8\fR \- compress images to within an inch of their lives
.
.SH "SYNOPSIS"
\fB28point8\fR [\fIiterations\fR] [\fIimage\fR\.\.\.] \fIimage\fR
.
.SH "DESCRIPTION"
The 28point8(1) command compresses input images with terrible JPEG compression\.
.
.P
The output filename is the original filename with "\-28p8" and the number of iterations appended
.
.SH "OPTIONS"
.
.TP
\fIimage\fR
any image file ImageMagick or GraphicsMagick support\.
.
.TP
[\fIiterations\fR]
how many times the image will be (badly) JPEG compressed\. The default is 1\.
.
.SH "SEE ALSO"
convert(1)
