.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "ANYPASTE" "1" "October 2014" "" "Jessica Stokes' Dotfiles"
.
.SH "NAME"
\fBanypaste\fR \- retrieve text from any clipboard
.
.SH "SYNOPSIS"
\fBanypaste\fR
.
.SH "DESCRIPTION"
The anypaste(1) command propagates the contents of the first available clipboard to STDOUT\. It is the counterpart to anycopy(1)\.
.
.P
It uses port 2225 to request pastes from an SSH client\'s clipboard, if available\.
.
.P
It uses pbcopy(1) to retrieve the clipboard on OS X, via \fBreattach\-to\-user\-namespace\fR if available\.
.
.P
xclip(1) is used where available\.
.
.P
As a last resort, text is retrieved from the file \fB~/\.anyclip\fR\.
.
.SH "SEE ALSO"
anycopy(1), pbcopy(1), xclip(1)
