.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "CHCASE" "1" "October 2014" "" "Jessica Stokes' Dotfiles"
.
.SH "NAME"
\fBchcase\fR \- transform the case of text input
.
.SH "SYNOPSIS"
\fBchcase\fR \fItransformation\fR \fItext\fR
.
.SH "DESCRIPTION"
The chcase(1) command converts supplied \fItext\fR between cases\.
.
.SH "TRANSFORMATIONS"
The \fItransformation\fR parameter accepts the following values;
.
.TP
\fBupper\fR, \fBup\fR, \fBu\fR
Transforms text to upper case\.
.
.TP
\fBlower\fR, \fBlow\fR, \fBlo\fR, \fBl\fR
Transforms text to lower case\.
.
.SH "SEE ALSO"
tr(1)
