.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "DOTFILES\-UNDOC" "1" "September 2017" "" "Jessica Stokes' Dotfiles"
.
.SH "NAME"
\fBdotfiles\-undoc\fR \- lists undocumented dotfiles scripts for the current platform
.
.SH "SYNOPSIS"
\fBdotfiles\-undoc\fR
.
.SH "DESCRIPTION"
The dotfiles\-undoc(1) command prints a list of dotfiles commands available on the current platform which do not currently have a manual page\.
