.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "FN" "1" "October 2014" "" "Jessica Stokes' Dotfiles"
.
.SH "NAME"
\fBfn\fR \- find a file by name
.
.SH "SYNOPSIS"
\fBfn\fR \fIname\fR
.
.SH "DESCRIPTION"
Searches current directory and all subdirectories for files with the supplied name\.
.
.P
There are two versions of this utility; on OS X, a version which makes use of mdfind(1) (which uses Spotlight\'s database), and on other platforms, a version which uses find(1)\.
