.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "GIFV" "1" "July 2019" "" "Jessica Stokes' Dotfiles"
.
.SH "NAME"
\fBgifv\fR \- convert a (probably gigantic) gif to an (hopefully small) mp4 video
.
.SH "SYNOPSIS"
\fBgifv\fR \fIgif\fR
.
.SH "DESCRIPTION"
Pass in a gif file and it will be converted to an mp4 video\.
.
.P
Output filename is the input filename but with an mp4 extension\.
.
.SH "SEE ALSO"
ffmpeg(1)
