.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "GIT\-DEVELOP" "1" "December 2016" "" "Jessica Stokes' Dotfiles"
.
.SH "NAME"
\fBgit\-develop\fR \- switch to the primary branch of the project
.
.SH "SYNOPSIS"
\fBgit develop\fR
.
.SH "DESCRIPTION"
Switches to the primary branch of the project; prefers "develop" but will fall back to "master"\.
.
.SH "SEE ALSO"
git\-changed(1) git\-checkout(1)
