.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "GIT\-PUSH\-ALL" "1" "September 2014" "Geoff Stokes' Dotfiles" "Geoff Stokes' Dotfiles"
.
.SH "NAME"
\fBgit\-push\-all\fR \- push data for current branch, as well as tags
.
.SH "SYNOPSIS"
\fBgit push\-all\fR
.
.SH "DESCRIPTION"
Pushes the current branch\'s data, as well as all tags\.
.
.P
In git(1)\-speak: Updates remote refs using local refs for the current HEAD, also pushes all refs under refs/tags\.
.
.P
Any parameters given are appended to the git\-push(1) command\.
.
.SH "SEE ALSO"
git\-push(1)
