.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "GRAVATAR" "1" "October 2014" "" "Jessica Stokes' Dotfiles"
.
.SH "NAME"
\fBgravatar\fR \- get Gravatar URL for an email address
.
.SH "SYNOPSIS"
\fBgravatar\fR [\fIemail\fR\.\.\.] \fIemail\fR
.
.SH "DESCRIPTION"
The gravatar(1) command outputs the URL to a Gravatar for a given email address
.
.SH "OPTIONS"
.
.TP
\fIemail\fR
Email address to fetch Gravatar URL for

