.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "IPGREP" "1" "October 2014" "" "Jessica Stokes' Dotfiles"
.
.SH "NAME"
\fBipgrep\fR \- calculate gzipped size of a file
.
.SH "SYNOPSIS"
\fBipgrep\fR
.
.SH "DESCRIPTION"
The ipgrep(1) command filters out valid, non\-loopback IP addresses from \fBSTDIN\fR\.
.
.SH "USAGE"
Pipe the output of ifconfig(8) into ipgrep(1) to list the IP addresses;
.
.IP "" 4
.
.nf

$ ifconfig | ipgrep
.
.fi
.
.IP "" 0
.
.SH "SEE ALSO"
ifconfig(8)
