.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "MANSI" "1" "October 2014" "" "Jessica Stokes' Dotfiles"
.
.SH "NAME"
\fBmansi\fR \- pass through to man(1) with colour enabled
.
.SH "SYNOPSIS"
\fBmansi\fR
.
.SH "DESCRIPTION"
The mansi(1) command runs man(1) with formatting overridden to be in colour\.
.
.SH "USAGE"
You can use any man(1) arguments on mansi(1) in the same way\.
.
.SH "SEE ALSO"
man(1)
