.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "MDWRAP" "1" "October 2014" "" "Jessica Stokes' Dotfiles"
.
.SH "NAME"
\fBmdwrap\fR \- wraps piped text for Markdown output
.
.SH "SYNOPSIS"
\fBmdwrap\fR
.
.SH "DESCRIPTION"
Pipe text into the mdwrap(1) command to have it wrapped in Markdown\'s ``` fence\.
.
.P
Output is then perfect for putting into GitHub Markdown snippets, or Slack\.
.
.P
Even better, pair it with pbcopy(1) to take it straight to the clipboard!
