.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "MOVIEME" "1" "February 2017" "" "Jessica Stokes' Dotfiles"
.
.SH "NAME"
\fBmovieme\fR \- create an animated gif from a movie file
.
.SH "SYNOPSIS"
\fBmovieme\fR \fIpath\fR [\fB\-\-start\fR \fIstart\-time\fR] [\fB\-\-duration\fR \fIduration\fR] [\fB\-\-framerate\fR \fIframerate\fR] [\fB\-\-delay\-start\fR \fIdelay\fR] [\fB\-\-delay\-end\fR \fIdelay\fR] [\fB\-\-size\fR \fIsize\fR] [\fB\-\-alternate\fR [\fB\-\-delay\-alternate\fR \fIdelay\fR]] [\fB\-\-no\-dither\fR] [\fB\-\-interactive\fR | \fB\-\-continue\fR] [\fB\-\-cleanup\fR]
.
.SH "DESCRIPTION"
The movieme(1) command creates an animated gif from a movie file
.
.SH "OPTIONS"
.
.TP
\fIpath\fR
path to the movie we\'re converting
.
.TP
\fB\-\-start\fR, \fB\-s\fR
start time within source video
.
.br
Default: \fI0\fR
.
.TP
\fB\-\-duration\fR, \fB\-d\fR
duration of video to convert
.
.br
Default: \fI5\fR
.
.TP
\fB\-\-framerate\fR, \fB\-f\fR
target framerate of the gif
.
.br
Default: \fI7\fR
.
.TP
\fB\-\-delay\-start\fR
milliseconds of delay on the \fIfirst\fR animation frame
.
.TP
\fB\-\-delay\-end\fR
milliseconds of delay on the \fIlast\fR animation frame
.
.TP
\fB\-\-alternate\fR, \fB\-a\fR
loop the animation back and forth; Imagemagick calls this a "patrol cycle"
.
.TP
\fB\-\-delay\-alternate\fR
milliseconds of delay on the \fImiddle\fR animation frame\. Can only be used with \fB\-\-alternate\fR
.
.TP
\fB\-\-no\-dither\fR, \fB\-n\fR
disable dithering of the output gif\. Can reduce file size in some cases
.
.TP
\fB\-\-size\fR
target size of the gif
.
.br
Default: 500x500>
.
.TP
\fB\-\-interactive\fR, \fB\-i\fR
extract frames, then exit to allow modifying individual frames
.
.TP
\fB\-\-continue\fR
continue conversion after calling \fB\-\-interactive\fR
.
.TP
\fB\-\-cleanup\fR
delete temporary files after completion\. Cannot be used with \fB\-\-interactive\fR
.
.SH "SEE ALSO"
ffmpeg(1), convert(1)
