.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "NPS" "1" "March 2015" "" "Jessica Stokes' Dotfiles"
.
.SH "NAME"
\fBnps\fR \- current Sonos playback information
.
.SH "SYNOPSIS"
\fBnps\fR
.
.SH "DESCRIPTION"
The nps(1) command displays the details of the current playing track on the first detected Sonos device on your network\.
.
.SH "SEE ALSO"
np(1)
