.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "NUNAME" "1" "October 2014" "" "Jessica Stokes' Dotfiles"
.
.SH "NAME"
\fBnuname\fR \- normalised operating system name
.
.SH "SYNOPSIS"
\fBnuname\fR
.
.SH "DESCRIPTION"
The nuname(1) command prints out a normalised operating system name\.
.
.P
On all systems, it outputs a lowercase, single\-word operating system name\. This is intended to work around the fact that Cygwin outputs kernel information with uname output, while other operating systems do not\.
.
.SH "SEE ALSO"
uname(1)
