.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "RETURNONEOF" "1" "October 2014" "" "Jessica Stokes' Dotfiles"
.
.SH "NAME"
\fBreturnOneOf\fR \- return one of the items given
.
.SH "SYNOPSIS"
\fBreturnOneOf\fR [\fIitem\fR\.\.\.] \fIitem\fR
.
.SH "DESCRIPTION"
The returnOneOf(1) command will print one of the given \fIitem\fRs to STDOUT at random\.
.
.SH "OPTIONS"
.
.TP
\fIitem\fR
item to potentially print to STDOUT\. Spaces are supported, but must be quoted or escaped\.

