.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "SELFIE" "1" "February 2015" "" "Jessica Stokes' Dotfiles"
.
.SH "NAME"
\fBselfie\fR \- put a nice, pretty picture of you on your desktop
.
.SH "SYNOPSIS"
\fBselfie\fR
.
.SH "DESCRIPTION"
The selfie(1) command uses imagesnap(1) to put a nice, pretty picture of you on your desktop\.
.
.SH "SEE ALSO"
imagesnap(1)
