.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "TMINUS" "1" "October 2014" "" "Jessica Stokes' Dotfiles"
.
.SH "NAME"
\fBtminus\fR \- print a human\-readable difference between two times
.
.SH "SYNOPSIS"
\fBtminus\fR [\fB\-h\fR] [\fB\-s time\fR] [\fB\-v\fR] \fIfinish\fR
.
.SH "DESCRIPTION"
The tminus(1) command will print a human\-readable difference between two times, using approximate values for seconds, minutes, hours, days, weeks, months, years and decades\.
.
.SH "USAGE"
.
.TP
\fB\-\-help\fR, \fB\-h\fR
print a help message and exit
.
.TP
\fB\-\-start time\fR, \fB\-s time\fR
set the start time for comparison; accepts Unix time
.
.TP
\fB\-\-verbose\fR, \fB\-v\fR
print debug information when calculating output
.
.TP
\fIfinish\fR
set the finish time for the comparison; accepts Unix time
.
.SH "SEE ALSO"
date(1)
