.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "TMX" "1" "October 2014" "" "Jessica Stokes' Dotfiles"
.
.SH "NAME"
\fBtmx\fR \- automatic tmux (re)attachment
.
.SH "SYNOPSIS"
\fBtmx\fR
.
.SH "DESCRIPTION"
The tmx(1) command creates or reconnects to a tmux(1) session\.
.
.SH "USAGE"
tmx(1) accepts no arguments\. if \fBtmux has\-session\fR returns a non\-error output, it calls \fBtmux attach\fR, otherwise, it calls \fBtmux\fR\. The exact behaviour will depend upon your tmux(1) configuration\.
.
.SH "SEE ALSO"
tmux(1)
