.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "XBMCPLAY" "1" "September 2014" "Geoff Stokes' Dotfiles" "Geoff Stokes' Dotfiles"
.
.SH "NAME"
\fBxbmcplay\fR \- tell an XBMC instance to open a URL
.
.SH "SYNOPSIS"
\fBxbmcplay\fR \fIurl\fR
.
.SH "DESCRIPTION"
Tells an XBMC instance to open the specified URL using the JSON RPC API\.
.
.SH "BUGS"
At present, the IP address of the XBMC instance is hard\-coded\. In the future, this will ideally use Bonjour to retrieve the first available XBMC instance on the current network\.
